package in.industrend.notification.api;
import java.net.URI; import java.net.http.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/internal/v1/notifications") public class NotificationController {
 public record OtpRequest(String mobile,String otp,String templateKey){} public record Delivery(String provider,String messageId,String status){}
 private final JdbcClient jdbc; private final String token,configUrl,msg91Key; private final HttpClient http=HttpClient.newHttpClient();
 public NotificationController(JdbcClient j,@Value("${services.internal-token}")String t,@Value("${services.config.url}")String c,@Value("${app.msg91.auth-key:}")String k){jdbc=j;token=t;configUrl=c;msg91Key=k;}
 @PostMapping("/otp") Delivery otp(@RequestHeader("X-Service-Token")String supplied,@RequestBody OtpRequest req){if(token.isBlank()||!token.equals(supplied))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.UNAUTHORIZED);var provider=config("notification.provider","mock");var id=UUID.randomUUID();var delivery="mock".equalsIgnoreCase(provider)?new Delivery("mock",UUID.randomUUID().toString(),"ACCEPTED"):msg91(req);jdbc.sql("insert into industrendindia.notification_deliveries(notification_id,channel,template_key,destination,provider,provider_message_id,status) values(:id,'SMS',:t,:d,:p,:m,:s)").param("id",id).param("t",req.templateKey()).param("d",req.mobile()).param("p",delivery.provider()).param("m",delivery.messageId()).param("s",delivery.status()).update();return delivery;}
 private Delivery msg91(OtpRequest req){var template=config("notification.msg91.template_id","");if(msg91Key.isBlank()||template.isBlank())throw new IllegalStateException("MSG91 credentials/template missing");try{var url=config("notification.msg91.base_url","https://control.msg91.com/api/v5/otp")+"?template_id="+template+"&mobile="+req.mobile()+"&otp="+req.otp();var request=HttpRequest.newBuilder(URI.create(url)).header("authkey",msg91Key).POST(HttpRequest.BodyPublishers.noBody()).build();var response=http.send(request,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2)throw new IllegalStateException("MSG91 rejected request");return new Delivery("msg91",null,"ACCEPTED");}catch(Exception e){throw new IllegalStateException("OTP delivery failed",e);}}
 private String config(String key,String fallback){try{var r=HttpRequest.newBuilder(URI.create(configUrl+"/internal/v1/config/"+key)).header("X-Service-Token",token).GET().build();var x=http.send(r,HttpResponse.BodyHandlers.ofString());return x.statusCode()==200?x.body():fallback;}catch(Exception e){return fallback;}}
}
